services:
  db:
    image: postgres:16-alpine
    container_name: lv_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lvflow}
      POSTGRES_USER: ${POSTGRES_USER:-lvuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lvpass}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pg_data:

